import fs from 'fs';

const rawCSV = `GSA - Gab de segurana em Armazm - Guarabira;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Criador;DJEANDERSON SOARES;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;MARIA KAMILLY DOS SANTOS;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;MARIA KAMILLY DOS SANTOS;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;DJEANDERSON SOARES;MARIA KAMILLY DOS SANTOS;MARIA KAMILLY DOS SANTOS
Data;09/01/2026;16/01/2026;23/01/2026;30/01/2026;06/02/2026;13/02/2026;20/02/2026;27/02/2026;06/03/2026;13/03/2026;20/03/2026;27/03/2026;03/04/2026;10/04/2026;17/04/2026;24/04/2026;01/05/2026;08/05/2026;15/05/2026;22/05/2026;29/05/2026;05/06/2026;12/06/2026;19/06/2026;26/06/2026;03/07/2026;10/07/2026;17/07/2026;24/07/2026;31/07/2026
%Percentual;83;78;98,4848;89;95,4545;96,9697;98,5294;98,4848;98,5294;96,9697;96,9697;95,4545;98,5294;96,9697;96,9697;97,0588;;95,4545;89,3939;;;;;;;;;;;
Comentrios;.;;.;empilhador Paulo esqueceu de remover a chave da ignio da empilhadeira e conferente estava trafegando fora do plano de trafego;rea precisando de repintura;empilhador Marivaldo esqueceu de tirar a chave da ignio da empilhadeira. Coaching aplicado;visibilidade da etiqueta ruim necessitando de troca;;;;colaborador no estava respeitando o limite de distancia da empilhadeira coaching aplicado;;colaborador Ozenildo esqueceu de remover colar . Coaching aplicado;;;;;colaborador esqueceu de remover a alina . Coaching aplicado;colaborador Dejean estava sem as luvas anticorte no momentodo manuseio;;;pilha inclinada com risco de tombamento. Gestor alertadado e pallet corrigido;colaborador estava utilizando apenas uma luva;Armazm estava com as luzes apagadas. A pessoa autorizada ligou as luzes;;;;conferente no estava respeitando a distancia minima da empilhadeira. Coaching aplicado;colaborador Dejean estava usando apenas uma mo ao pegar a ala da garrafeira. Coaching foi aplicado;
GSA - Gab de segurana em Armazm - Guarabira;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
Em qual operao foi feito o GSA?;Guarabira;Guarabira;GUARABIRA;Guarabira;GUARABIRA;Guarabira;guarabira;GUARABIRA;GUARABIRA;GUARABIRA;GUARABIRA;Guarabira;GUARABIRA;GUARABIRA;GUARABIRA;GUARABIRA;;GUARABIRA;GUARABIRA;;;;;;;;;;;
Piso - O piso est limpo e seco?;Sim;Sim;Sim;Sim;No;Sim;No;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;No;sim;No;No;No;No
Piso - O piso est uniforme sem presena de ondulaes que ofeream riscos de acidentes?;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Empilhamento de produto - O empilhamento de produtos segue o padro do manual de segurana em armazns e almoxarifados? Verificar se existe ruas com lotes de produtos inclinados.;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;No;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Equipamentos de combate a Incndio - Os extintores e hidrantes esto desobstruido? Foi realizado inspeo mensal? Esto em boas condies?;timo;timo;timo;timo;Bom;Bom;Bom;timo;timo;timo;Bom;Bom;timo;timo;timo;timo;;Bom;timo;Bom;timo;timo;timo;Bom;Ruim;Ruim;Ruim;Ruim;Ruim;Ruim
Plataformas e escadas - Todas as plataformas, escadas e guarda-corpo esto em boas condies de uso e identificadas? Sem presena de amassados, soldas quebradas, rodas danificadas, etc.;N/A;timo;N/A;N/A;Bom;Bom;N/A;timo;N/A;N/A;N/A;N/A;N/A;timo;N/A;N/A;;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
Equipamentos de elevao (racks, prateleiras, paleteiras, etc), so inspecionados? Possuem etiquetas de liberao ou segregao?;timo;N/A;N/A;timo;timo;timo;Ruim;timo;timo;Bom;Bom;timo;timo;timo;timo;timo;;Ruim;Bom;timo;timo;Bom;timo;timo;timo;timo;timo;timo;timo;timo
Paineis eltricos - H sinalizao adequada e as portas esto fechadas? Existem gambiarras eltricas?;timo;timo;timo;timo;Bom;Bom;timo;timo;timo;Bom;timo;timo;timo;Bom;timo;timo;;Bom;timo;timo;timo;timo;timo;timo;Bom;Bom;Bom;Bom;Bom;Bom
Armazenagem de prod. Qumicos -  Todos os Prod. qumicos esto armazenados adequadamente e segue o padro de incompatibilidade? Existe bacia de conteno?;timo;timo;timo;timo;Bom;Bom;timo;Sim;Sim;Sim;Sim;Sim;Sim;timo;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Chuveiros de Emergncia - H chuveiros emergenciais com lava olhos prximo a rea de produtos qumicos e carregamento de baterias - Todos esto em perfeito funcionamento (puxadores e alavancas das vlvulas) e saindo gua suficiente e uniforme?;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;timo;N/A;;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
Sinalizao - A rea demarcada para circulao de pedestres esta bem sinalizada existe placas de sinalizao, esto adequadas?;timo;timo;timo;timo;Ruim;Ruim;Bom;timo;timo;Bom;Bom;timo;timo;timo;Bom;Bom;;Bom;Bom;timo;Bom;Bom;Bom;timo;Ruim;Ruim;Ruim;Ruim;Ruim;Ruim
Sistema de trava-quedas - A linha de vida, monovias, troles, e trava quedas? Esto em perfeitas condies de uso?;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
Trava-roda esta sendo utilizado no carregamento, retorno de rota e puxada? Esto em bons estado de uso? O trava-rodas de Puxada est no padro correto? Esto em bons estados de uso?;timo;timo;timo;timo;N/A;N/A;Bom;timo;timo;Bom;N/A;timo;timo;Ruim;timo;timo;;N/A;timo;Bom;timo;N/A;Bom;timo;timo;timo;timo;timo;timo;timo
Paleteiras esta sendo utilizada corretamente? Esto em bom estado de uso?;timo;timo;timo;timo;timo;timo;Ruim;timo;timo;timo;Bom;timo;timo;timo;timo;timo;;Bom;timo;timo;Bom;timo;timo;timo;timo;timo;timo;timo;timo;timo
Espelhos convexos - Os espelhos convexos esto em boas condies e na quantidade necessria a rea?;N/A;N/A;N/A;N/A;Ruim;Ruim;N/A;timo;timo;N/A;Bom;timo;timo;Ruim;timo;timo;;N/A;N/A;timo;timo;Bom;N/A;timo;timo;timo;timo;timo;timo;timo
Iluminao - A iluminao das reas ( Logistica, Amarrao, Repack, Of. Empilhadeira e Pit Stop) esto em boas condies?;timo;timo;timo;timo;Bom;Bom;timo;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;No;Sim;Sim;Sim;Sim;Sim;Sim
Empilhadeiras - Todas as empilhadeiras esto em boas condies de trabalho (Sinal sonoro de r, luz de r, faris, giroflex, buzina, protetos de teto (grade), freios, pneus, retrovisores, extintor dentro da validade, cinto de segurana com dispositiv;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Oficina de empilhadeiras - A oficina de empilhadeiras est limpa, isenta de leos no piso e organizada?;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;timo;N/A;N/A;N/A;N/A;N/A;;N/A;N/A;N/A;timo;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A;N/A
Ferramentas - As ferramentas/estiletes de segurana utilizados na rea esto em boas condies de uso?;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
rea de abastecimento - O abastecimento  feito por colaborador treinado? Seguindo todos padres de segurana?;N/A;N/A;N/A;N/A;timo;timo;N/A;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Pessoas - Os funcionrios retiram qualquer tipo de adorno durante acesso s reas produtivas? Verificar se esto seguindo este procedimento.;Sim;Sim;Sim;Sim;Sim;Sim;Bom;Sim;Sim;Sim;Sim;Sim;No;Sim;Sim;Sim;;No;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
"Pessoas - Todos os funcionrios prprios e terceiros esto utilizando os EPIs necessarios (capacete com jugular; bota de segurana; culos de segurana; colete ou uniforme refletivo? Todos esto em boas condies de uso?";timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;Bom;Bom;;Bom;Bom;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Pessoas - Todos os funcionrios prprios e terceiros esto seguindo os procedimentos de segurana de movimentao manual (seguem a postura correta no manuseio de produtos)?;timo;timo;timo;timo;timo;timo;Bom;timo;timo;timo;timo;timo;timo;timo;timo;timo;;timo;Bom;timo;timo;timo;timo;timo;timo;timo;timo;OTIMO;No;timo
Pessoas - Funcionrios conhecem a rota de fuga em caso de emergncia e os pontos de encontro? Orientar os colaboradores sobre o ponto de apoio : guarita, em caso de emergncia.;timo;timo;timo;timo;Bom;Bom;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Pessoas - As pessoas esto afastadas pelo menos a 5 metros das empilhadeiras quando esto em operao, conforme solicitados no manual de segurana em armazns e almoxarifados?;timo;timo;timo;timo;Bom;Bom;Bom;timo;Bom;Bom;Ruim;Bom;Bom;Bom;timo;timo;;Ruim;Ruim;timo;timo;Ruim;Bom;timo;timo;timo;timo;ruim;timo;timo
5s - Todos os objetos disponiveis na rea so realmente necessrios? rea est organizada e limpa?;timo;timo;timo;timo;Bom;Bom;Bom;timo;timo;Bom;timo;timo;timo;Bom;timo;timo;;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Coleta seletiva - Os materiais esto separados corretamente para sua devida destinao.;timo;timo;timo;timo;Bom;Bom;Bom;timo;timo;timo;timo;timo;timo;timo;timo;timo;;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Aproxima o corpo da carga abaixando-se e executando ergonomia correta?;Sim;Sim;Sim;Sim;Sim;Sim;Bom;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Est empurrando a paleteira ao inves de puxar?;timo;timo;timo;timo;timo;timo;timo;timo;timo;Bom;timo;timo;timo;timo;timo;timo;;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Utilizam as travas do piking e a segregao homem mquina?;timo;timo;timo;timo;bom;bom;N/A;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Est ultilizando luvas na operao de empilhadeira?;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;No;Sim;Sim;Sim;No;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Desliga a empilhadeira e abaixa os garfos quando algum se aproxima? Orientar colaborador sobre este procedimento.;timo;timo;timo;timo;timo;timo;Bom;Bom;Bom;Bom;Bom;timo;timo;timo;timo;timo;;Ruim;Bom;timo;timo;Bom;Ruim;timo;timo;timo;timo;timo;timo;timo
Realiza carregamento de bateria seguindo todos padres de segurana?;N/A;timo;timo;timo;timo;timo;N/A;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Faz o giro 360 em carretas e caminhes antes de carregar e descarregar?;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;;timo;timo;timo;timo;timo;N/A;timo;timo;timo;timo;timo;timo;timo
Faz o uso do cinto de segurana ?;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Verificar durante a semana se quando no carregamento ou descarregamento de produtos, a chave da ignio  retirada.;timo;timo;timo;ruim;timo;ruim;Bom;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim
Desce do caminho utilizando os trs pontos de apoio?;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo;timo
Os colaboradores do armazm sabe ou se lembra qual foi o ltimo treinamento? Colocar ao lado qual foi a reposta dos colaboradores.;timo;timo;timo;timo;timo;timo;timo;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim;Sim`;

console.log("Raw CSV length:", rawCSV.length);
